"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.API_RESPONSE_CODE = exports.API_CLIENT_REQUEST_METHOD = void 0;
var API_CLIENT_REQUEST_METHOD;
(function (API_CLIENT_REQUEST_METHOD) {
    API_CLIENT_REQUEST_METHOD["GET"] = "GET";
    API_CLIENT_REQUEST_METHOD["POST"] = "POST";
    API_CLIENT_REQUEST_METHOD["PUT"] = "PUT";
    API_CLIENT_REQUEST_METHOD["DELETE"] = "DELETE";
    API_CLIENT_REQUEST_METHOD["PATCH"] = "PATCH";
})(API_CLIENT_REQUEST_METHOD = exports.API_CLIENT_REQUEST_METHOD || (exports.API_CLIENT_REQUEST_METHOD = {}));
var API_RESPONSE_CODE;
(function (API_RESPONSE_CODE) {
    API_RESPONSE_CODE[API_RESPONSE_CODE["SUCCESS"] = 0] = "SUCCESS";
    API_RESPONSE_CODE[API_RESPONSE_CODE["FAILED"] = 1] = "FAILED";
    API_RESPONSE_CODE[API_RESPONSE_CODE["ERROR"] = 2] = "ERROR";
    API_RESPONSE_CODE[API_RESPONSE_CODE["EXCEPTION"] = 3] = "EXCEPTION";
})(API_RESPONSE_CODE = exports.API_RESPONSE_CODE || (exports.API_RESPONSE_CODE = {}));
